### ISSUE TITLE
Unexpected response from modbus device

### ISSUE THREAD

**Issue by anarion80** [borpin/ha_komfovent_config#1]
Hello.

I've started using your config for my own komfovent, and everything is working fine, but after some time (hours?) I can see the following error in the logs:

`2022-03-20 20:45:56 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1

2022-03-20 20:46:11 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1

2022-03-20 20:46:11 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1

2022-03-20 20:46:26 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1

2022-03-20 20:46:26 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1`

It is related to the switches that go from Intensive/Boost to normal. Do you have any idea what is going on here and how to avoid this error?

**Comment by borpin** [comment]
Hi, That is odd.

Is the Firmware on the unit upto date?

If you comment out the sensors and switches related to `address: 5` (which is register 4) does this go away?

Else check and see if removing the `address: 4` sensors and switches makes it go.

I am certainly not seeing this.

**Comment by anarion80** [comment]
Good point about firmware. I updated yesterday to the latest version, but unfortunately it did not help. Whole night it was spamming with the error:

```
2022-03-23 10:16:52 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:16:52 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:07 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:07 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:07 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:22 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:22 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:22 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:37 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:37 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
2022-03-23 10:17:37 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1
```

I couldn't determine the trigger for when this happens, seemingly without any action from me. 
I will now remove the switches from config and see.

**Comment by borpin** [comment]
I am also suddenly seeing these occasionally. I'll investigate.

**Comment by anarion80** [comment]
After removing only the switches:

```
# Away,Intensive or Boost off, switch to Normal
      # Switch Normal Off go to Away
      # - name: "Komfovent Switch Away"
      #   # slave: 2
      #   address: 4
      #   command_on: 1
      #   command_off: 2
      #   verify:
      # - name: "Komfovent Switch Normal"
      #   # slave: 2
      #   address: 4
      #   command_on: 2
      #   command_off: 1
      #   verify:
      # - name: "Komfovent Switch Intensive"
      #   # slave: 2
      #   address: 4
      #   command_on: 3
      #   command_off: 2
      #   verify:
      # - name: "Komfovent Switch Boost"
      #   # slave: 2
      #   address: 4
      #   command_on: 4
      #   command_off: 2
      #   verify:
      # - name: "Komfovent Switch Kitchen"
      #   # slave: 2
      #   address: 4
      #   command_on: 5
      #   command_off: 2
      #   verify:
```
I can no longer see those errors.

I can see 
```
2022-03-24 11:47:13 ERROR (SyncWorker_8) [homeassistant.components.modbus.modbus] Pymodbus: komfovent: Exception Response(131, 3, SlaveBusy)
```
a couple times a night but I don't think that's related...

**Comment by borpin** [comment]
Thanks. You will get the `slavebusy` occasionally.

thing is, Address 4, is register 5 which implies the error message is not correct.

Do you see the original error messages when switching between modes? It could just be that the command has not been executed by the time the python library tries to verify it.

**Comment by anarion80** [comment]
Yes, after enabling the switches back, the errors show up very soon (a couple seconds) after clicking the switch, and the value in the unexpected response seem to be correlated to `command_on` value:

```
2022-03-24 14:54:25 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 4
2022-03-24 14:54:40 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 1

```

**Comment by borpin** [comment]
So are you getting the old value in the Error?

**Comment by anarion80** [comment]
No, I'm getting the new, target value in the error.

And also, something's not right with the other switches. Meaning when I have Normal switch On, and I click Intensive, I get:
```
2022-03-24 16:36:26 ERROR (MainThread) [homeassistant.components.modbus.base_platform] Unexpected response from modbus device slave 0 register 4, got 0x 3
```
the Intensive switch turns On, but the Normal does not turn off:

![obraz](https://user-images.githubusercontent.com/2185791/159953781-50f07ad4-cf3d-445f-8fdb-83be808152e5.png)

**Comment by borpin** [comment]
Short answer, don't know. I am seeing the same and also if I switch on the Intensive from the Komfovent web page as well.

It must be to do with the `verify`. Similar issue raised (bit not solved I don't think) here https://community.home-assistant.io/t/fans-and-modbus-automation-komfovent/378355

It may be this needs to be done via a script.

I am in the process of doing a Lovelace config which I'll upload once done. For this operation, I write directly to the register which works :)

![image](https://user-images.githubusercontent.com/1322749/160081589-0827889f-a24a-4247-a3cb-5d9ac969783f.png)

```yaml
type: horizontal-stack
cards:
  - type: custom:button-card
    entity: sensor.komfovent_operation_mode
    color: grey
    tap_action:
      action: call-service
      service: modbus.write_register
      service_data:
        address: 4
        hub: Komfovent
        unit: 1
        value: 1
    hold_action:
      action: none
    name: Away
    show_name: true
    icon: mdi:home-export-outline
    color_type: card
    state:
      - value: Away
        color: CornflowerBlue
  - type: custom:button-card
    entity: sensor.komfovent_operation_mode
    color: grey
    tap_action:
      action: call-service
      service: modbus.write_register
      service_data:
        address: 4
        hub: Komfovent
        unit: 1
        value: 2
    hold_action:
      action: none
    name: Normal
    show_name: true
    icon: mdi:home-account
    color_type: card
    state:
      - value: Normal
        color: CornflowerBlue
  - type: custom:button-card
    entity: sensor.komfovent_operation_mode
    color: grey
    tap_action:
      action: call-service
      service: modbus.write_register
      service_data:
        address: 4
        hub: Komfovent
        unit: 1
        value: 3
    hold_action:
      action: none
    name: Intensive
    show_name: true
    icon: mdi:weather-windy
    color_type: card
    state:
      - value: Intensive
        color: CornflowerBlue
  - type: custom:button-card
    entity: sensor.komfovent_operation_mode
    color: grey
    tap_action:
      action: call-service
      service: modbus.write_register
      service_data:
        address: 4
        hub: Komfovent
        unit: 1
        value: 4
    hold_action:
      action: none
    name: Boost
    show_name: true
    icon: mdi:fan
    color_type: card
    state:
      - value: Boost
        color: CornflowerBlue
```

**Comment by anarion80** [comment]
Yes, looks like it. So I will redo mine as well to use scripts. Thanks!

**Comment by borpin** [comment]
If you have something that works, feel free to share. I will removed the switches (unless I can get them working with the Verify option).

**Comment by anarion80** [comment]
I did it just like you and I'm quite happy for now:

```
- type: custom:button-card
  entity: sensor.komfovent_operation_mode
  name: Poza Domem
  icon: hass:home-export-outline
  show_state: false
  tap_action:
    action: call-service
    service: script.komfovent_set_away
  template:
    - basic
  state:
    - value: Away
      styles:
        icon:
          - color: var(--state-icon-active-color)
        card:
          - color: rgba(0, 0, 0, 0.6)
          - background-color: rgba(255, 255, 255, 0.8)

- type: custom:button-card
  entity: sensor.komfovent_operation_mode
  name: Normalny
  show_icon: true
  icon: hass:home-account
  show_state: false
  tap_action:
    action: call-service
    service: script.komfovent_set_normal
  template:
    - basic
  state:
    - value: Normal
      styles:
        icon:
          - color: var(--state-icon-active-color)
        card:
          - color: rgba(0, 0, 0, 0.6)
          - background-color: rgba(255, 255, 255, 0.8)

- type: custom:button-card
  entity: sensor.komfovent_operation_mode
  name: Intensywny
  show_icon: true
  icon: hass:weather-windy
  show_state: false
  tap_action:
    action: call-service
    service: script.komfovent_set_intensive
  template:
    - basic
  state:
    - value: Intensive
      styles:
        icon:
          - color: var(--state-icon-active-color)
        card:
          - color: rgba(0, 0, 0, 0.6)
          - background-color: rgba(255, 255, 255, 0.8)
- type: custom:button-card
  entity: sensor.komfovent_operation_mode
  name: Turbo
  show_icon: true
  icon: hass:fan
  show_state: false
  tap_action:
    action: call-service
    service: script.komfovent_set_boost
  template:
    - basic
  state:
    - value: Boost
      styles:
        icon:
          - color: var(--state-icon-active-color)
        card:
          - color: rgba(0, 0, 0, 0.6)
          - background-color: rgba(255, 255, 255, 0.8)

- type: custom:button-card
  entity: switch.komfovent_switch_power
  name: Zasilanie
  icon: hass:power-cycle
  show_state: false
  template:
    - basic
```
![obraz](https://user-images.githubusercontent.com/2185791/160101351-ffd4e12a-aaa1-4feb-8fbd-e38a289abc41.png)
